spring:
  application:
    name: resumeGenerator
  config:
    import:
    - optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: riyas
    password: riyas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081