
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resumegen
    username: riyas
    password: riyas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082